stages:
  - build
  - docker

backend-build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn -B -DskipTests package

frontend-build:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build

docker-build:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker compose build
